### ISSUE TITLE
(1,000,000 SC) - DeFi Skynet Hackathon Challenge

### ISSUE THREAD

**Issue by MSevey** [NebulousLabs/Skynet-Hive#3]
## Challenge Description
Use the api at https://siasky.net to integrate Skynet into your hack. Your hack must include the ability to either upload or download from Skynet (or both!) as a core feature.

## Challenge Prize
A prize of 500,000 SC (estimated value: $700) each will be awarded to the top two projects that have the best Skynet integration in their hack. Apps will be judged by looking at the quality of the user experience, the creativity of the Skynet integration, and most importantly how useful the Skynet integration is to other people.

## Submission Requirements
 - The project must be open source
 - Skynet must be a fundamental element of the application.
 - The app must do something that is useful and interesting.
 - The app will score better if it has greater appeal to a wider audience
 - Demo videos are strongly recommended for complete submissions

How involved or difficult the application is will not be considered. If a very useful and interesting app can be created with very little effort, this app will still qualify for the grand prize and all other prizes.

Example apps and ideas which would qualify for prizes:
- Uniswap on Skynet:
https://siasky.net/EAByx9EagK71BoS1za93Q9s0l7xSe7VG6P8aUEtJK4mmDQ/build/index.html#/swap

Other potential ideas:
- Hosting your DeFi app on Skynet
- A tool to bookmark and share other Skynet applications and files
- A desktop app for browsing Skynet without using a centralized portal
- Migrating existing DeFi apps to Skynet

## Judging Criteria
Submissions will be judged on the following:
 - How applicable is the application and how likely is it to be used by others
 - Potential positive impact on the Skynet ecosystem
 - Works on mainnet

**Comment by skynethubio** [comment]
How do I register for this Hackathon ? can existing app with new features count as valid submission?

**Comment by MSevey** [comment]
@skynethubio https://hackathon.money/

We will most likely give preference to new apps, but it doesn't hurt to submit :-)
